Todo app
Elijahdre/React--To-Do-List pull request #1
Opened 2022-09-16 01:52 UTC by Elijahdre

In this the PR, a todo app was built to learn the core concepts of react

2022-09-16 10:40 UTC, DuaneDave requested changes
## Hey @Elijahdre 👋 

You have done well putting in much effort on this project! 👏  
There are some changes you must implement before merging this PR.

### Highlights
Your project is almost complete!

- No Linters errors
- Confident use of es6 syntax 
- Awesome UI

### Required Changes ♻️ 
Check the comments under the review.

### Optional Suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code more professional._

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Cheers and Happy coding! 🥂

2022-09-16 10:40 UTC, DuaneDave commented on src/components/InputTodo.js
> +/* eslint-disable no-alert */
Please enable eslint to allow it run checks on your project to ensure you are following javascript best practices

2022-09-16 10:40 UTC, DuaneDave commented on src/components/Header.js
> +        }}
[OPTIONAL] consider limiting the use of inline styles in your JSX snippet and keep styling in a separate CSS file.  This separation of concern will improve the overall readability of your code

2022-09-16 10:40 UTC, DuaneDave commented on src/components/TodosList.js
> +/* eslint-disable react/destructuring-assignment, react/prop-types  */
Please enable this linter rule and use restructuring assignment. The destructuring assignment will make your code more readable and clean.

instead of `TodoList = (props)` use `TodoList = ({ id, handleChangeProps, deleteTodoProps, setUpdate })` and replace all occurrence of `props.xyz` with their respective assignment from the destructure

2022-09-17 15:27 UTC, Elijahdre commented on src/components/InputTodo.js
> +/* eslint-disable no-alert */
Thank you 👍

2022-09-17 21:52 UTC, DuaneDave approved these changes
## Hey @Elijahdre 👋 

You have done well implementing all required changes👏, please go ahead and merge this PR 

### Highlights
Your project is complete!

- No Linters errors
- Confident use of es6 syntax 
- Awesome UI
- Quick implementation of required changes

### Status:  Approved 🟢 

### Optional Suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code more professional._

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Cheers and Happy coding! 🥂

2022-09-20 14:32 UTC, merged